FROM python:3.9-slim as production

ENV PYTHONUNBUFFERED=1
WORKDIR /apps/

COPY requirements/prod.txt ./requirements/prod.txt
RUN pip install -r ./requirements/prod.txt

COPY manage.py  ./manage.py
COPY pyvenv.cfg ./pyvenv.cfg
COPY djweb ./djweb

EXPOSE 8000